group_name: SMC_Test
configs:

  - config_descr: Vary_only_Dimension
    posterior_type: MvNormal
    varying_attribute: dimension
    varying_values: [2,5,10,15,18,30]
    mu: ZERO_30
    cov: ID_30

  - config_descr: Varing_only_Tails
    posterior_type: StudentT
    varying_attribute: nu
    varying_values: [2.1,3,4,5,30]
    sigma: 1
    mu: 0

  - config_descr: Varing_Tails_with_high_Dimension
    posterior_type: MvStudentT
    varying_attribute: nu
    varying_values: [2.1,3,4,5,30]
    scale: ID_30
    mu: ZERO_30

  - config_descr: Vary_Dimension_with_heavy_Tails
    posterior_type: MvStudentT
    varying_attribute: dimension
    varying_values: [2,5,10,15,18,30]
    mu: ZERO_30
    nu: 2.1
    scale: ID_30





