group_name: Global_Test
configs:

  - config_descr: Base_Gaussian
    posterior_type: Normal
    varying_attribute: mu
    varying_values: [0]
    mu: 0
    sigma: 1

  - config_descr: Vary_only_Correlation
    posterior_type: MvNormal
    varying_attribute: correlation
    varying_values: [0.0, 0.8, 0.9, 0.95, 0.98, 0.99, 0.995, 0.999]
    mu: ZERO_2
    cov: ID_2 


  - config_descr: Vary_only_Dimension
    posterior_type: MvNormal
    varying_attribute: dimension
    varying_values: [2,10,15,20,25,30,40,60, 100]
    mu: ZERO_100
    cov: ID_100


  - config_descr: Varing_only_Tails
    posterior_type: StudentT
    varying_attribute: nu
    varying_values: [1.1, 1.5, 1.8, 2.1, 2.5, 3, 3.5, 4, 5, 10, 30, 120]
    sigma: 1
    mu: 0

  - config_descr: Varying_only_Mode_distance
    posterior_type: Mixture
    component_types: ["Normal", "Normal"]
    component_params:
      - mu: 0
        sigma: 1
      - mu: 10
        sigma: 1
    weights: [0.5, 0.5]
    varying_attribute: mu
    varying_values: [4, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16]
    varying_component: 1




