group_name: Correlation
configs:

  - config_descr: sweep_corr_mix
    posterior_type: Mixture
    varying_attribute: correlation
    varying_values: [0.0, 0.5, 0.9]
    component_types:
      - MvNormal
      - MvNormal
      - MvNormal
    component_params:
      - mu: [0, 0]
        cov: ID_2 
      - mu: [10, 10]
        cov: ID_2 
      - mu: [50, 100]
        cov: ID_2
    weights: [0.33, 0.33, 0.34]

