group_name: single_mv_normal
configs:
  - config_descr: Mv_normal_5d
    posterior_type: Mixture
    component_types:
      - MvNormal
      - MvNormal
      - MvNormal
    component_params:
      - mu: [10, 10, 20, 30, 30]
        cov: ID_5
      - mu: [20, 20, 40, 60, 60]
        cov: ID_5
      - mu: [30, 30, 60, 90, 90]
        cov: ID_5
    weights: [0.33, 0.33, 0.34]
    varying_attribute: dimension_mv
    varying_values: [5, 4, 3, 2]
