group_name: Dimension
configs:

  - config_descr: Vary_Dimension_Tails__Corr
    posterior_type: MvStudentT
    varying_attribute: dimension
    varying_values: [2,5,10,15,30]
    mu: ZERO_30
    nu: 2.1
    scale: HIGH_30

  - config_descr: Vary_Dimension_Tails_MM
    posterior_type: Mixture
    component_types: ["MvStudentT", "MvStudentT"]
    component_params:
      - mu: ZERO_30
        scale: ID_30
        nu: 2.1
      - mu: FIRST_13_30
        scale: ID_30
        nu: 2.1
    weights: [0.5, 0.5]
    varying_attribute: dimension
    varying_values: [2,5,10,15,30]

  - config_descr: Vary_Dimension_MM_Correlation
    posterior_type: Mixture
    component_types: ["MvNormal", "MvNormal"]
    component_params:
      - mu: ZERO_30
        cov: HIGH_30
      - mu: FIRST_13_30
        cov: HIGH_30
    weights: [0.5, 0.5]
    varying_attribute: dimension
    varying_values: [2,5,10,15,30]

  - config_descr: Vary_Dimension_MM_Tails_Correlation
    posterior_type: Mixture
    component_types: ["MvStudentT", "MvStudentT"]
    component_params:
      - mu: ZERO_30
        scale: HIGH_30
        nu: 2.1
      - mu: FIRST_13_30
        scale: HIGH_30
        nu: 2.1
    weights: [0.5, 0.5]
    varying_attribute: dimension
    varying_values: [2,5,10,15,30]









