group_name: Multimodal_Distance
configs:

  - config_descr: Varying_only_Dimension
    posterior_type: Mixture
    component_types: ["MvNormal", "MvNormal"]
    component_params:
      - mu: ZERO_10
        cov: ID_10
      - mu: ZERO_10
        cov: ID_10
    weights: [0.5, 0.5]
    varying_attribute: "dimension"
    varying_values: [1,2,3,10]










  
