group_name: multimodal
configs:

  - config_descr: Varying_only_Mode_distance
    posterior_type: Mixture
    component_types: ["Normal", "Normal"]
    component_params:
      - mu: 0
        sigma: 1
      - mu: 10
        sigma: 1
    weights: [0.5, 0.5]
    varying_attribute: mu
    varying_values: [6, 10, 12, 15, 22]
    varying_component: 1






  
