group_name: multimodal
configs:

  - config_descr: Mixture_of_3_Normal_2d_vary_mu_diagonal
    posterior_type: Mixture
    varying_attribute: mu
    varying_component: 2
    varying_values:
      - [2, 2]
      - [5, 5]
      - [10, 10]
      - [20, 20]
      - [40, 40]
    component_types:
      - MvNormal
      - MvNormal
      - MvNormal
    component_params:
      - mu: [0, 0]
        cov:
          - [1.0, 0.0]
          - [0.0, 1.0]
      - mu: [-5, -5]
        cov:
          - [1.0, 0.0]
          - [0.0, 1.0]
      - mu: [2, 2]
        cov:
          - [1.0, 0.0]
          - [0.0, 1.0]
    weights: [0.33, 0.33, 0.34]



  
