group_name: multimodal
configs:


  - config_descr: Mixture_of_10_MvNormal_on_circle
    posterior_type: Mixture
    varying_component: 0
    varying_attribute: mu
    varying_values: 
      - [10.0, 0.0]
    component_types:
      - MvNormal
      - MvNormal
      - MvNormal
      - MvNormal
      - MvNormal
      - MvNormal
      - MvNormal
      - MvNormal
      - MvNormal
      - MvNormal
    component_params:
      - mu: [10.0, 0.0]
        cov: [[0.5, 0.0], [0.0, 0.5]]
      - mu: [8.09, 5.88]
        cov: [[0.5, 0.0], [0.0, 0.5]]
      - mu: [3.09, 9.51]
        cov: [[0.5, 0.0], [0.0, 0.5]]
      - mu: [-3.09, 9.51]
        cov: [[0.5, 0.0], [0.0, 0.5]]
      - mu: [-8.09, 5.88]
        cov: [[0.5, 0.0], [0.0, 0.5]]
      - mu: [-10.0, 0.0]
        cov: [[0.5, 0.0], [0.0, 0.5]]
      - mu: [-8.09, -5.88]
        cov: [[0.5, 0.0], [0.0, 0.5]]
      - mu: [-3.09, -9.51]
        cov: [[0.5, 0.0], [0.0, 0.5]]
      - mu: [3.09, -9.51]
        cov: [[0.5, 0.0], [0.0, 0.5]]
      - mu: [8.09, -5.88]
        cov: [[0.5, 0.0], [0.0, 0.5]]
    weights: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]







  
