group_name: Multimodal_Distance
configs:

  - config_descr: Varying_only_Mode_distance
    posterior_type: Mixture
    component_types: ["MvNormal", "MvNormal"]
    component_params:
      - mu: ZERO_2
        cov: ID_2
      - mu: ZERO_2
        cov: ID_2
    weights: [0.5, 0.5]
    varying_attribute: mu
    varying_values: [[10,0], [12,0], [14,0]]
    varying_component: 1









  
