group_name: Multimodal_Distance
configs:

  - config_descr: Varying_only_Mode_distance
    posterior_type: Mixture
    component_types: ["MvNormal", "MvNormal"]
    component_params:
      - mu: ZERO_5
        cov: ID_5
      - mu: ZERO_5
        cov: ID_5
    weights: [0.5, 0.5]
    varying_attribute: mu
    varying_values: [[4,0,0,0,0], [6,0,0,0,0]]
    varying_component: 1









  
