group_name: multimodal
configs:

  - config_descr: Normal_and_student_t
    posterior_type: Mixture
    varying_attribute: mu
    varying_values: [5, 10, 20]
    varying_component: 1
    component_types: ["Normal", "StudentT"]
    component_params:
      - mu: 0
        sigma: 1
      - nu: 3
        mu: 20
        sigma: 2
    weights: [0.6, 0.4]

  - config_descr: Mixture_of_Normal
    posterior_type: Mixture
    varying_attribute: mu
    varying_values: [8, 10, 12, 14, 16, 18, 20, 22]
    varying_component: 1
    component_types: ["Normal", "Normal"]
    component_params:
      - mu: 0
        sigma: 1
      - mu: 10
        sigma: 1
    weights: [0.7, 0.3]

  
  - config_descr: Mixture_of_Normal_2d_diagonal
    posterior_type: Mixture
    varying_attribute: mu
    varying_values:
      - [5, 5]
      - [10, 10]
      - [20, 20]
      - [50, 10]
    varying_component: 1
    component_types:
      - MvNormal
      - MvNormal
    component_params:
      - mu: [0, 0]
        cov:
          - [1.0, 0.5]
          - [0.5, 1.0]
      - cov:
          - [2.0, 0.3]
          - [0.3, 2.0]
    weights: [0.7, 0.3]


  - config_descr: Mixture_of_Normal_2d_varied
    posterior_type: Mixture
    varying_attribute: mu
    varying_values:
      - [5, 5]
      - [10, -10]
      - [20, 20]
      - [50, 10]
      - [80, 0]
    varying_component: 1
    component_types:
      - MvNormal
      - MvNormal
    component_params:
      - mu: [0, 0]
        cov:
          - [1.0, 0.5]
          - [0.5, 1.0]
      - cov:
          - [2.0, 0.3]
          - [0.3, 2.0]
    weights: [0.7, 0.3]

  - config_descr: Mixture_of_Normal_3d
    posterior_type: Mixture
    varying_attribute: mu
    varying_values:
      - [3, 3, 3]
      - [6, 6, 6]
      - [10, 10, 10]
      - [20, 20, 20]
    varying_component: 1
    component_types: ["MvNormal", "MvNormal"]
    component_params:
      - mu: [0, 0, 0]
        cov:
          - [1, 0.5, 0.3]
          - [0.5, 1, 0.4]
          - [0.3, 0.4, 1]
      - cov:
          - [2, 0.3, 0.2]
          - [0.3, 2, 0.1]
          - [0.2, 0.1, 2]
    weights: [0.7, 0.3]
 


  
