group_name: Only_attr
configs:


  - config_descr: Varying_only_Mode_distance
    posterior_type: Mixture
    component_types: ["MvNormal", "MvNormal"]
    component_params:
      - mu: ZERO_2
        cov: ID_2
      - mu: ZERO_2
        cov: ID_2
    weights: [0.5, 0.5]
    varying_attribute: "mm"
    varying_values: [6,8, 10]










