group_name: nightmare
configs:

  - config_descr: SMC_Hard_SpikeMixture_5d
    posterior_type: Mixture
    varying_attribute: mu
    varying_values:
      - [10, 10, 10, 10, 10]
      - [20, 20, 20, 20, 20]
    varying_component: 1
    component_types: ["MvNormal", "MvNormal"]
    component_params:
      - mu: [0, 0, 0, 0, 0]
        cov:
          - [5, 0, 0, 0, 0]
          - [0, 5, 0, 0, 0]
          - [0, 0, 5, 0, 0]
          - [0, 0, 0, 5, 0]
          - [0, 0, 0, 0, 5]
      - cov:
          - [0.01, 0, 0, 0, 0]
          - [0, 0.01, 0, 0, 0]
          - [0, 0, 0.01, 0, 0]
          - [0, 0, 0, 0.01, 0]
          - [0, 0, 0, 0, 0.01]
    weights: [0.9, 0.1]
