group_name: Tails
configs:

  - config_descr: Varing_only_Tails
    posterior_type: StudentT
    varying_attribute: nu
    varying_values: [2.1,3,4,5,30]
    sigma: 1
    mu: 0

  - config_descr: Varing_Tails_with_high_Dimension
    posterior_type: MvStudentT
    varying_attribute: nu
    varying_values: [2.1,3,4,5,30]
    scale: ID_30
    mu: [10, 10, 10, 10, 10, 20, 20, 20, 20, 20,
         30, 30, 30, 30, 30, 40, 40, 40, 40, 40,
         50, 50, 50, 50, 50, 60, 60, 60, 60, 60]


  - config_descr: Varing_Tails_with_high_Correlation
    posterior_type: MvStudentT
    varying_attribute: nu
    varying_values: [2.1,3,4,5,30]
    scale: HIGH_2
    mu: [0, 0]


  - config_descr: Varing_Tails_with_high_Dimension_and_high_Correlation
    posterior_type: MvStudentT
    varying_attribute: nu
    varying_values: [2.1,3,4,5,30]
    scale: HIGH_30
    mu: [10, 10, 10, 10, 10, 20, 20, 20, 20, 20,
         30, 30, 30, 30, 30, 40, 40, 40, 40, 40,
         50, 50, 50, 50, 50, 60, 60, 60, 60, 60]



