group_name: Tails
configs:

  - config_descr: Vary_Tails_with_high_Multimodality
    posterior_type: Mixture
    component_types: ["MvStudentT", "MvStudentT"]
    component_params:
      - mu: ZERO_2
        scale: ID_2
        nu: 2.1
      - mu: [13, 0]
        scale: ID_2
        nu: 2.1
    weights: [0.5, 0.5]
    varying_attribute: nu
    varying_values: [2.1, 50]



