group_name: three_attr_dim
configs:

  - config_descr: Vary_Dimension_with_Corr_and_Tails
    posterior_type: MvStudentT
    varying_attribute: dimension
    varying_values: [2, 3, 5, 8, 15, 30]
    mu: ZERO_30
    nu: 2.1
    scale: HIGH_30

  - config_descr: Vary_Dimension_with_Corr_and_MM
    posterior_type: Mixture
    component_types: ["MvNormal", "MvNormal"]
    component_params:
      - mu: ZERO_30
        cov: HIGH_30
      - mu: ZERO_30
        cov: HIGH_30
    weights: [0.5, 0.5]
    varying_attribute: dimension
    varying_values: [2, 3, 5, 8, 15, 30]

  - config_descr: Vary_Dimension_with_Tails_and_MM
    posterior_type: Mixture
    component_types: ["MvStudentT", "MvStudentT"]
    component_params:
      - mu: ZERO_30
        scale: ID_30
        nu: 2.1
      - mu: ZERO_30
        scale: ID_30
        nu: 2.1
    weights: [0.5, 0.5]
    varying_attribute: dimension
    varying_values: [2, 3, 5, 8, 15, 30]








