group_name: Multimodal_Distance
configs:

  - config_descr: Varying_Mode_Distance_with_high_Dimension
    posterior_type: Mixture
    component_types: ["MvNormal", "MvNormal"]
    component_params:
      - mu: ZERO_30
        cov: ID_30
      - mu: ZERO_30
        cov: ID_30
    weights: [0.5, 0.5]
    varying_attribute: "mm"
    varying_values: [5, 8, 10, 12, 15, 18]
    varying_component: 1









  
