save_plots_and_csv_per_run: false                          # if True, save plots for each run 
save_traces: false                                         # if True, save traces to NetCDF files
trace_plots: first_run_only                                # options: "none", "first_run_only", "all"
save_individual_traceplots_per_dim: false                  # if True and posterior multidimensional, save individual trace plots for each dimension
plot_traces_in_notebook: false                             # if True, plot traces in notebook            
samplers: ["HMC", "Metro", "DEMetro_Z", "SMC"  ]           # options: "Metro", "HMC", "DEMetro", "DEMetro_Z"
logging_level: ERROR                                       # options: DEBUG, INFO, ERROR
plot_first_sample: true                                    # if True, plot the first sample of each chain
save_extra_scatter: true                                  # if True, save additional scatter plots for each sampler
save_pairwise_scatter: true                               # if True, save pairwise scatter plots for each sampler
do_mmd: false                                              # if True, compute MMD statistics
do_mmd_rff: true                                          # if True, compute MMD statistics with RFF