group_name: circle
configs:

  - config_descr: circle_test
    posterior_type: Circle
    varying_attribute: circle_modes
    varying_values: [4, 6, 8, 10, 12]
    component_type: MvNormal
    component_number: 10
    radius: 8.0
    weights: equal








  
