group_name: Multimodal_Distance
configs:

  - config_descr: Vary_Correlation_with_high_Multimodality
    posterior_type: Mixture
    component_types: ["MvNormal", "MvNormal"]
    component_params:
      - mu: ZERO_2
        cov: ID_2
      - mu: [10, 0]
        cov: ID_2
    weights: [0.5, 0.5]
    varying_attribute: correlation
    varying_values: [0.0, 0.3, 0.5, 0.9, 0.99]


  - config_descr: Vary_Dimension_with_high_Multimodality
    posterior_type: Mixture
    component_types: ["MvNormal", "MvNormal"]
    component_params:
      - mu: ZERO_30
        cov: ID_30
      - mu: FIRST_10_30
        cov: ID_30
    weights: [0.5, 0.5]
    varying_attribute: dimension
    varying_values: [2,5,10,15,30]







  
