group_name: Correlation
configs:

  - config_descr: Vary_only_Correlation
    posterior_type: MvNormal
    varying_attribute: correlation
    varying_values: [0.0, 0.3, 0.5, 0.9, 0.99]
    mu: [0, 0]
    cov: ID_2 

  - config_descr: Vary_Correlation_with_heavy_Tails
    posterior_type: MvStudentT
    varying_attribute: correlation
    varying_values: [0.0, 0.3, 0.5, 0.9, 0.99]
    mu: [0, 0]
    scale: ID_2 
    nu: 2.1

  - config_descr: Vary_Correlation_with_high_Dimension
    posterior_type: MvNormal
    varying_attribute: correlation
    varying_values: [0.0, 0.3, 0.5, 0.9, 0.99]
    mu: [10, 10, 10, 10, 10, 20, 20, 20, 20, 20,
         30, 30, 30, 30, 30, 40, 40, 40, 40, 40,
         50, 50, 50, 50, 50, 60, 60, 60, 60, 60]
    cov: ID_30

  - config_descr: Vary_Correlation_with_heavy_Tails_and_high_Dimension
    posterior_type: MvStudentT
    varying_attribute: correlation
    varying_values: [0.0, 0.3, 0.5, 0.9, 0.99]
    mu: [10, 10, 10, 10, 10, 20, 20, 20, 20, 20,
         30, 30, 30, 30, 30, 40, 40, 40, 40, 40,
         50, 50, 50, 50, 50, 60, 60, 60, 60, 60]
    scale: ID_30
    nu: 2.1







